"""added shipper and order

Revision ID: 2d4e0c45cea0
Revises: 11d8b752566c
Create Date: 2022-10-12 17:19:24.196988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4e0c45cea0'
down_revision = '11d8b752566c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
