"""product changed unit price to sale price

Revision ID: 4c320641b4a7
Revises: 6965a32c9b5a
Create Date: 2022-10-12 17:55:32.943473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c320641b4a7'
down_revision = '6965a32c9b5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('product', 'unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('product', 'sale_price')
    # ### end Alembic commands ###
