"""product discontinued not nullable

Revision ID: 4e54b76b9780
Revises: b535af6cc9e1
Create Date: 2022-10-15 11:41:22.372796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e54b76b9780'
down_revision = 'b535af6cc9e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'discontinued',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'discontinued',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
