"""added photo to product category

Revision ID: 61925ba228c4
Revises: e0c9841ba166
Create Date: 2022-10-12 15:36:01.055920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61925ba228c4'
down_revision = 'e0c9841ba166'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_category', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_category', 'photo')
    # ### end Alembic commands ###
