"""product_suppliar relation fix

Revision ID: 6965a32c9b5a
Revises: fabf76cea948
Create Date: 2022-10-12 17:45:54.501395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6965a32c9b5a'
down_revision = 'fabf76cea948'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_supplier_product_id_fkey', 'product_supplier', type_='foreignkey')
    op.create_foreign_key(None, 'product_supplier', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_supplier', type_='foreignkey')
    op.create_foreign_key('product_supplier_product_id_fkey', 'product_supplier', 'supplier', ['product_id'], ['id'])
    # ### end Alembic commands ###
