"""product can be featured

Revision ID: b373965b63ed
Revises: 4e54b76b9780
Create Date: 2022-10-15 12:12:04.489341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b373965b63ed'
down_revision = '4e54b76b9780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('featured', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'featured')
    # ### end Alembic commands ###
