"""added constraints to strings

Revision ID: b535af6cc9e1
Revises: f476e2868f69
Create Date: 2022-10-14 19:26:15.684109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b535af6cc9e1'
down_revision = 'f476e2868f69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('contact_first_name', sa.String(length=25), nullable=True))
    op.add_column('supplier', sa.Column('contact_last_name', sa.String(length=25), nullable=True))
    op.drop_column('supplier', 'contact_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('supplier', 'contact_last_name')
    op.drop_column('supplier', 'contact_first_name')
    # ### end Alembic commands ###
