"""added extra columns to order

Revision ID: f476e2868f69
Revises: e0a31f9eea6d
Create Date: 2022-10-14 11:57:20.924699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f476e2868f69'
down_revision = 'e0a31f9eea6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('vat', sa.Numeric(precision=2, scale=2), server_default='0', nullable=False))
    op.add_column('order', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    op.drop_column('order', 'vat')
    # ### end Alembic commands ###
