"""base model finished

Revision ID: fabf76cea948
Revises: 2d4e0c45cea0
Create Date: 2022-10-12 17:40:32.912502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fabf76cea948'
down_revision = '2d4e0c45cea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_supplier',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('supplier_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'supplier_id', name='unique_product_supplier')
    )
    op.add_column('product', sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('product', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'photo')
    op.drop_column('product', 'unit_price')
    op.drop_table('product_supplier')
    # ### end Alembic commands ###
