insert into address (address, city, region, postal_code, country) values ('7019 La Follette Terrace', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('4 Almo Center', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('28 Birchwood Road', 'Budapest', 'Budapest', '1111', 'HU');
insert into address (address, city, region, postal_code, country) values ('8 Vahlen Park', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('8588 Moose Point', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('88 Springview Drive', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('1770 Sachtjen Road', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('88898 Londonderry Street', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('3686 Westridge Alley', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('62 Amoth Trail', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('82849 Memorial Court', 'Budapest', 'Budapest', '1024', 'HU');
insert into address (address, city, region, postal_code, country) values ('61988 Duke Circle', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('010 Ridgeview Lane', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('6 Marcy Plaza', 'Budapest', 'Budapest', '1111', 'HU');
insert into address (address, city, region, postal_code, country) values ('76808 Scofield Junction', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('9254 Northridge Plaza', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('0006 Mariners Cove Court', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('25161 Bobwhite Terrace', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('0863 Golf Course Plaza', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Loomis Trail', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('91 Haas Plaza', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('3911 Derek Street', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('48 Transport Avenue', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('15468 Dorton Street', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('5 Westerfield Place', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('09373 Crownhardt Junction', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('5 Commercial Drive', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Truax Junction', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('19224 Duke Street', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('057 Bartillon Hill', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('78 Southridge Junction', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('14 Oriole Pass', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('67 Mandrake Point', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('7994 Larry Avenue', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('18 Nova Lane', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('4 Eastlawn Trail', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('7790 Parkside Way', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('6 Commercial Terrace', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('0 Graceland Lane', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('95 Coolidge Street', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('06 Burning Wood Park', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('25774 Beilfuss Avenue', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('76 Little Fleur Park', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('3 Transport Junction', 'Budapest', 'Budapest', '1111', 'HU');
insert into address (address, city, region, postal_code, country) values ('58288 Veith Circle', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('6 Arrowood Court', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('506 Lotheville Parkway', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('05 Green Ridge Court', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('71610 Alpine Road', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('8763 Sutteridge Park', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('5105 Hintze Alley', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('4 Waxwing Junction', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('9056 Roxbury Terrace', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('293 Pine View Point', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('75179 Dapin Place', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('622 Marquette Center', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('71 Thierer Crossing', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('5 Ronald Regan Terrace', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('432 Scofield Circle', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('8 Welch Terrace', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('27044 Tennessee Point', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('76 Westend Street', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('40288 Acker Street', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('7 Stoughton Park', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('417 Helena Plaza', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('7572 Sutteridge Crossing', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('62917 Lawn Park', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('037 Dottie Park', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('3872 Esker Point', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('8076 Lawn Way', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('592 Charing Cross Junction', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('51 Fordem Terrace', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('9339 Lakewood Gardens Place', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('1 Hoffman Circle', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('74579 Bartillon Crossing', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('0396 Morning Park', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('68 Evergreen Center', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('8 Golf View Crossing', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('411 Hovde Terrace', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('8797 2nd Park', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('734 Merchant Park', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('4 Elka Hill', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('5641 Miller Terrace', 'Budapest', 'Budapest', '1111', 'HU');
insert into address (address, city, region, postal_code, country) values ('347 Vera Crossing', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('6401 Toban Center', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('5 Columbus Drive', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('6 Acker Pass', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('53837 Del Sol Pass', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Golf Terrace', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('91959 Elmside Parkway', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('66843 Bayside Trail', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 Memorial Road', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('10 Larry Court', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('597 Birchwood Street', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('425 Westerfield Lane', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('8543 Di Loreto Drive', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 Dayton Lane', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('05 Fairview Circle', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('033 Morrow Plaza', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('34 Clyde Gallagher Pass', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('3 Melby Avenue', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('4592 Miller Court', 'Budapest', 'Budapest', '1024', 'HU');
insert into address (address, city, region, postal_code, country) values ('53455 Dennis Park', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Crescent Oaks Avenue', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('6939 Saint Paul Road', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('399 Goodland Road', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Judy Avenue', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('41 Towne Circle', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 Delladonna Avenue', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('66 Golf Course Street', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('5865 Riverside Plaza', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('4032 Morning Road', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('97033 Oneill Court', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('5886 Kings Court', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('48 Trailsway Circle', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('521 Northridge Lane', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('57 Maryland Crossing', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('00284 Basil Terrace', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('67 Sommers Pass', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('8 Everett Center', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Lakeland Place', 'Budapest', 'Budapest', '1024', 'HU');
insert into address (address, city, region, postal_code, country) values ('993 Heath Park', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('6926 Montana Terrace', 'Budapest', 'Budapest', '1111', 'HU');
insert into address (address, city, region, postal_code, country) values ('7064 Delladonna Avenue', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('076 Derek Center', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('1 Spenser Circle', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('523 School Terrace', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('89 Blackbird Point', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('05 Bultman Junction', 'Budapest', 'Budapest', '1111', 'HU');
insert into address (address, city, region, postal_code, country) values ('427 Lunder Road', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('6855 Continental Trail', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('656 1st Road', 'Budapest', 'Budapest', '1024', 'HU');
insert into address (address, city, region, postal_code, country) values ('82 Garrison Crossing', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('86559 Pankratz Street', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('24776 Pond Street', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('4 Anzinger Place', 'Budapest', 'Budapest', '1024', 'HU');
insert into address (address, city, region, postal_code, country) values ('23 Brickson Park Alley', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('3806 Randy Center', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('16942 Commercial Parkway', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('734 Sugar Court', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('57065 Dwight Trail', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('1 Londonderry Avenue', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('7320 Trailsway Pass', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('32029 Bluejay Drive', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('11908 Loftsgordon Circle', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('63 Grim Circle', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('98 Sheridan Place', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('235 Birchwood Point', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('09 Burning Wood Alley', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('472 Russell Street', 'Budapest', 'Budapest', '1024', 'HU');
insert into address (address, city, region, postal_code, country) values ('4 Westridge Center', 'Budapest', 'Budapest', '1111', 'HU');
insert into address (address, city, region, postal_code, country) values ('429 Hooker Lane', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('01 Drewry Alley', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 Tony Crossing', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('6463 Bluejay Alley', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Londonderry Crossing', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('4408 Elka Road', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('43 Monica Point', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('9975 Bartillon Alley', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('14 Reinke Trail', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('38862 Cherokee Alley', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('46637 Tony Plaza', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('807 Leroy Court', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('64603 Weeping Birch Court', 'Budapest', 'Budapest', '1024', 'HU');
insert into address (address, city, region, postal_code, country) values ('2520 Garrison Park', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('3 Hanson Park', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('36516 Mendota Street', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('52 Dapin Circle', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('0 Heath Street', 'Budapest', 'Budapest', '1024', 'HU');
insert into address (address, city, region, postal_code, country) values ('1 Corscot Drive', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('60736 Schmedeman Place', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('646 Anzinger Trail', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('8 Homewood Park', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('08 Holy Cross Parkway', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 Kensington Park', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('124 Cordelia Point', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Fairfield Plaza', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('180 Butternut Road', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('0 Jana Lane', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('8978 Springs Alley', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('0 Rutledge Junction', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('99201 Norway Maple Place', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('29 Bartelt Court', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('6199 Clemons Terrace', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('31 Fisk Center', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('59 Columbus Place', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('3548 3rd Circle', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('6 Melvin Alley', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('01 Oneill Center', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('1010 Fairfield Avenue', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('89 Roth Terrace', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('29949 Esker Pass', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('72351 Blaine Crossing', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('5351 Kingsford Street', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('48050 School Pass', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('8 Northland Terrace', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('458 Bobwhite Park', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('74351 Sunnyside Avenue', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('52 Thackeray Place', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 Magdeline Drive', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('2 Eastlawn Circle', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('8920 Badeau Street', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('4 Dennis Avenue', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('7 Alpine Court', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('08 Charing Cross Place', 'Budapest', 'Budapest', '1181', 'HU');
insert into address (address, city, region, postal_code, country) values ('0517 Meadow Valley Lane', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('015 Northport Crossing', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('286 Lyons Place', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('07250 Center Road', 'Budapest', 'Budapest', '1122', 'HU');
insert into address (address, city, region, postal_code, country) values ('9501 Nevada Place', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('155 Annamark Drive', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('0 Johnson Circle', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('99682 Meadow Ridge Plaza', 'Budapest', 'Budapest', '1097', 'HU');
insert into address (address, city, region, postal_code, country) values ('382 Shopko Road', 'Budapest', 'Budapest', '1136', 'HU');
insert into address (address, city, region, postal_code, country) values ('680 Meadow Vale Crossing', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('82 Garrison Avenue', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('08156 Pepper Wood Place', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 Packers Road', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('34 Toban Alley', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('9524 Forest Dale Terrace', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 North Pass', 'Budapest', 'Budapest', '1062', 'HU');
insert into address (address, city, region, postal_code, country) values ('700 Sullivan Court', 'Budapest', 'Budapest', '1158', 'HU');
insert into address (address, city, region, postal_code, country) values ('5572 Northport Alley', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('45 Green Ridge Place', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('7 Mendota Alley', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('8 Hudson Crossing', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('45397 Redwing Place', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('28155 Northwestern Terrace', 'Budapest', 'Budapest', '1194', 'HU');
insert into address (address, city, region, postal_code, country) values ('928 North Point', 'Budapest', 'Budapest', '1046', 'HU');
insert into address (address, city, region, postal_code, country) values ('10 Bay Street', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('9 Dunning Hill', 'Győr', 'Győr-Moson-Sopron', '9009', 'HU');
insert into address (address, city, region, postal_code, country) values ('922 Sutteridge Junction', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('389 Stoughton Pass', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('04 Morrow Terrace', 'Sopron', 'Győr-Moson-Sopron', '9404', 'HU');
insert into address (address, city, region, postal_code, country) values ('62453 Longview Avenue', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('58 Grasskamp Hill', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('6 2nd Hill', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('75 Maple Place', 'Győr', 'Győr-Moson-Sopron', '9024', 'HU');
insert into address (address, city, region, postal_code, country) values ('3738 Bashford Point', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('45 Pearson Court', 'Budapest', 'Budapest', '1035', 'HU');
insert into address (address, city, region, postal_code, country) values ('5 Mitchell Point', 'Budapest', 'Budapest', '1239', 'HU');
insert into address (address, city, region, postal_code, country) values ('704 Maple Circle', 'Budapest', 'Budapest', '1111', 'HU');
insert into address (address, city, region, postal_code, country) values ('43 Paget Crossing', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('58 Springview Terrace', 'Budapest', 'Budapest', '1213', 'HU');
insert into address (address, city, region, postal_code, country) values ('30 Kensington Center', 'Budapest', 'Budapest', '1147', 'HU');
insert into address (address, city, region, postal_code, country) values ('0307 Bluejay Junction', 'Budapest', 'Budapest', '1074', 'HU');
insert into address (address, city, region, postal_code, country) values ('0488 Drewry Alley', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('13 Buena Vista Drive', 'Budapest', 'Budapest', '1086', 'HU');
insert into address (address, city, region, postal_code, country) values ('74950 Morning Hill', 'Szolnok', 'Jász-Nagykun-Szolnok', '5009', 'HU');
insert into address (address, city, region, postal_code, country) values ('91 Algoma Pass', 'Budapest', 'Budapest', '1024', 'HU');
